Waiting for the cluster to shut down
This resolves the issue with mysqld trying to create a daemon process
when the old one hasn't been removed yet

Signed-off-by: Mateusz Blaszkowski <mateusz.blaszkowski@intel.com>

diff --git a/mariadb-galera/templates/configmaps/mariadb-galera-seed.sh.yaml.j2 b/mariadb-galera/templates/configmaps/mariadb-galera-seed.sh.yaml.j2
--- a/mariadb-galera/templates/configmaps/mariadb-galera-seed.sh.yaml.j2
+++ b/mariadb-galera/templates/configmaps/mariadb-galera-seed.sh.yaml.j2
@@ -52,6 +52,19 @@ data:
 
         # Restart database.
         mysqladmin -uroot -p"{{ database.root_password }}" shutdown
+
+        # Wait for the mariadb server to shut down
+        SHUTDOWN_TIMEOUT=60
+        while [[ -f /var/lib/mysql/mariadb.pid ]]; do
+            if [[ ${SHUTDOWN_TIMEOUT} -gt 0 ]]; then
+                let SHUTDOWN_TIMEOUT-=1
+                sleep 1
+            else
+                echo "MariaDB instance couldn't be properly shut down"
+                exit 1
+            fi
+        done
+
         su -s /bin/bash mysql -c "mysqld_safe --defaults-file=/etc/my.cnf \
                                     --console \
                                     --wsrep-new-cluster \
