Add another race condition prevention in readiness probe.

diff --git a/rabbitmq/templates/configmaps/rabbitmq-scripts.sh.yaml.j2 b/rabbitmq/templates/configmaps/rabbitmq-scripts.sh.yaml.j2
--- a/rabbitmq/templates/configmaps/rabbitmq-scripts.sh.yaml.j2
+++ b/rabbitmq/templates/configmaps/rabbitmq-scripts.sh.yaml.j2
@@ -113,6 +113,13 @@ data:
         fi
         return 0
     }
+
+    case $(marker-state) in
+        missing)
+            echo "$LP Startup marker missing, probably probe was executed too early"
+            exit 1
+            ;;
+    esac
     
     if main; then
         rc=0
